name: CI

on: [push, pull_request]

permissions: {}

jobs:
    build:
        name: Bun
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                  submodules: recursive

            - name: Install Bun
              uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Typecheck
              run: bun run typecheck

            - name: Lint
              run: bunx biome ci
